# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroClie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=140, null=True)),
                ('apellido', models.CharField(blank=True, max_length=140, null=True)),
                ('matricula', models.IntegerField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='file')),
            ],
        ),
    ]
